name: Monthly Maintenance Audit
on:
  schedule:
    - cron: '55 19 * * *'

jobs:
  create_issue: 
    name: Create Monthly Maintenance Audit Issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Monthly Maintenance Audit Issue
        uses: imjohnbo/issue-bot@v3.3.4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          labels: 'maintenance, backend, audit'
          title: Maintenance & Dependancy Update - ${{ steps.data.outputs.data}}
          body: |
            Update Outdated Packages and Dependancies
          
            **Acceptance Criteria**
          
            - Update any outdate packages
            - Audit current packeages for vulnerabilities
            - Update any dependancies with vulnerabilities
          # project-type: user
          # project: 1
          # column: Backlog
          pinned: true
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
