name: Monthly Maintenance Audit
on:
  schedule:
    - cron: '10 14 * * *'
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  
jobs:
  create_issue: 
    name: Create Monthly Maintenance Audit Issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create Monthly Maintenance Audit Issue
        uses: imjohnbo/issue-bot@v3
        with:
          labels: 'maintenance, backend, audit'
          title: 'Maintenance & Dependancy Update'
          body: |
            Update Outdated Packages and Dependancies
          
            **Acceptance Criteria**
          
            - Update any outdate packages
            - Audit current packeages for vulnerabilities
            - Update any dependancies with vulnerabilities
          pinned: true
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  add_issues:
    needs: create_issue
    runs-on: ubuntu-latest
    steps:
      - name: Assign to One Project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: https://github.com/users/TheFlyer1983/projects/1
          column_name: 'Backlog'
